-- Personal look. Loaded after the defaults, so values here win.
-- Windows stay square. Uncomment a block to change it.

-- hl.config({
--   general = {
--     gaps_in = 0,
--     gaps_out = 0,
--     border_size = 0,
--     layout = "scrolling",
--   },
--   decoration = {
--     rounding = 0,
--     dim_inactive = true,
--     dim_strength = 0.15,
--   },
--   animations = {
--     enabled = false,
--   },
-- })
